set_lib_cell_purpose -include cts {*/AND2X2_LVT}
set_lib_cell_purpose -include cts {*/AND2X1_LVT}
set_lib_cell_purpose -include cts {*/AND2X4_LVT}
set_lib_cell_purpose -include cts {*/AO22X1_LVT}
set_lib_cell_purpose -include cts {*/AO22X2_LVT}
set_lib_cell_purpose -include cts {*/AOI22X1_LVT}
set_lib_cell_purpose -include cts {*/AOI22X2_LVT}
set_lib_cell_purpose -include cts {*/CGLNPRX2_LVT}
set_lib_cell_purpose -include cts {*/CGLNPRX8_LVT}
set_lib_cell_purpose -include cts {*/CGLPPRX2_LVT}
set_lib_cell_purpose -include cts {*/CGLPPRX8_LVT}
set_lib_cell_purpose -include cts {*/MUX21X1_LVT}
set_lib_cell_purpose -include cts {*/MUX21X2_LVT}
set_lib_cell_purpose -include cts {*/LSUPX1_LVT}
set_lib_cell_purpose -include cts {*/LSUPX2_LVT}
set_lib_cell_purpose -include cts {*/LSUPX4_LVT}
set_lib_cell_purpose -include cts {*/LSUPX8_LVT}
